{
 "title": "Services Healthcheck",
 "tags": [
  "monitoring",
  "services"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Успешные проверки",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(site_id) (increase(service_check_success_total[5m]))",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Ошибки проверок",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(site_id) (increase(service_check_fail_total[5m]))",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Время ответа (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_check_duration_ms_bucket[5m])) by (le,site_id))",
     "legendFormat": "95% {{site_id}}"
    }
   ]
  },
  {
   "title": "Отправленные алерты",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(site_id) (increase(service_alert_sent_total[5m]))",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Отслеживаемых сайтов",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 6, "h": 4 },
   "targets": [
    { "expr": "service_sites_tracked", "legendFormat": "sites" }
   ]
  }
 ]
}